/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on November 27, 2019 */



@font-face {
    font-family: 'arvobold';
    src: url('arvo-bold-webfont.woff2') format('woff2'),
         url('arvo-bold-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'arvobold_italic';
    src: url('arvo-bolditalic-webfont.woff2') format('woff2'),
         url('arvo-bolditalic-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'arvoitalic';
    src: url('arvo-italic-webfont.woff2') format('woff2'),
         url('arvo-italic-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}